linters:
  disable:
    - errcheck
  enable:
    - asciicheck
    - contextcheck 
    - gofmt
    - govet
    - usestdlibvars

linters-settings:
    govet:
      disable:
        - stdmethods
    lll:
      line-length: 100
run:
  skip-dirs:
    - tutorial/go/gen-go
