linters:
  disable:
    - errcheck
  enable:
    - asciicheck
    - errorlint
    - govet
    - usestdlibvars

  linters-settings:
    gci:
      - standard
      - default
      - prefix(github.com/apache/thrift)
    govet:
      disable:
        - stdmethods
    lll:
      line-length: 100
run:
  skip-dirs:
    - tutorial/go/gen-go
