linters:
  disable:
    - errcheck
  enabled:
    - errorlint
    - gofumpt
    - govet
    - lll

  linters-settings:
    govet:
      disable:
        - stdmethods
    lll:
      line-length: 100
run:
  skip-dirs:
    - tutorial/go/gen-go
